# Generated by Django 5.1 on 2024-08-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0002_purchasecartmodel_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseCartModel',
        ),
    ]
