# Generated by Django 5.1.2 on 2024-10-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0005_purchasemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
