# Generated by Django 5.1.2 on 2024-10-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0006_purchasemodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemodel',
            name='status',
            field=models.CharField(default='Processing', max_length=50),
        ),
    ]
