# Generated by Django 5.1 on 2024-08-25 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_product', '0005_review_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='products',
        ),
        migrations.AddField(
            model_name='review',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cloth_product.product'),
        ),
    ]
