# Generated by Django 5.1 on 2024-08-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_product', '0006_remove_review_products_review_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(upload_to='Product_images'),
        ),
    ]
