# Generated by Django 5.1 on 2024-08-27 17:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_product', '0008_alter_product_image_alter_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Product_images'),
        ),
    ]
