# Generated by Django 5.1 on 2024-08-28 07:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth_product', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Product_images'),
        ),
    ]
